apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: ''
  labels:
    appgroup: ''
    version: v1
  name: wx-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: wx-test
      version: v1
  template:
    metadata:
      labels:
        app: wx-test
        version: v1
    spec:
      containers:
        - name: container-1
          image: swr.cn-north-4.myhuaweicloud.com/testapp/demo01:gin
          imagePullPolicy: IfNotPresent
          env:
            - name: PAAS_APP_NAME
              value: wx-test
            - name: PAAS_NAMESPACE
              value: default
            - name: PAAS_PROJECT_ID
              value: 0a7255e09a00f35a2fe2c0013ad66d51
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: 512Mi
      imagePullSecrets:
        - name: default-secret
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
      initContainers: []
      volumes: []
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  progressDeadlineSeconds: 600


---
apiVersion: v1
kind: Service
metadata:
  name: wx-test-67059
  labels:
    app: wx-test
    version: v1
  namespace: default
  annotations: {}
spec:
  selector:
    app: wx-test
    version: v1
  ports:
    - name: cce-service-0
      targetPort: 8080
      nodePort: 0
      port: 8080
      protocol: TCP
  type: ClusterIP
